### ISSUE TITLE
ipv6 documentation

### ISSUE THREAD

**Issue by Tejeev** [rancher/rke2-docs#235]
IPV6 is becoming more and more important. Our customers are asking more questions about it and we should flesh out our docs on the subject.  Here are some very loose findings from someone on our support team which were provided to a customer in an attempt to help.  This should be doublechecked and fleshed out for a doc.
- When configuring dual stack, ipv6 first then ipv4 does not work.
- Switch the order, and things will start to work. This appears to be an upstream thing
- Using ipv6 only is where the challenge is. [Upstream Calico](https://docs.tigera.io/calico/latest/networking/ipam/ipv6#enable-ipv6-only) reports the steps to take in order to do this, but we haven't seen this actually work yet (possibly because we might not need the ingress anymore due to ipv4 routing. This is just a guess).
- We also have some very limited [notes in the RKE2 docs](https://docs.rke2.io/networking/basic_network_options?_highlight=ipv#ipv6-setup).
- Here is a [reddit post](https://www.reddit.com/r/kubernetes/comments/77b5s8/kubernetes_in_ipv6_only/?rdt=34136) by user that said they got IPv6-Only working.
- RKE2 supports IPv6, but Rancher does not.
- There may be some complication with cattle-cluster-agent connecting to rancher-server pods over a dual stack network.

**Comment by brandond** [comment]
> When configuring dual stack, ipv6 first then ipv4 does not work.

This is supposed to work. Possibly fixed by https://github.com/k3s-io/k3s/pull/10511
>> Fix IPv6 primary node-ip handling
>> The loadbalancer does not properly bind to the ipv6 loopback when the node has an ipv6 primary node ip, as the comma-separated flag value containing both IPs cannot be parsed as a valid ipv6 address.

> Using ipv6 only is where the challenge is

This should also work as far as I know. What specifically is not working for you?

> RKE2 supports IPv6, but Rancher does not.

Same question... what bits of rancher are you seeing that don't support ipv6? There were some bugs around ipv6 address handling in the past (specifically around properly encoding ipv6 address literals) but I thought they were resolved.

**Comment by flrichar** [comment]
I was able to mock-up almost of the questions above in my lab. However, the dual-stack support relied heavily on things like the ingress controller and CNI.  In regards to the documentation, perhaps we can add a blurb about the versions where that first bullet point was fixed in the 10511 issue.

I think situations where customers have ipv6-only networks are typically specialty networks, so factors like Rancher become moot, because everything Rancher touches would need to be dual-stack or ipv6-only (like Github). It might be moot because these specialty networks are probably air-gapped and have local private repos, etc, so those issues may be resolved by the environmental context.

**Comment by Tejeev** [comment]
@dereknola I'm curious why this is being marked as not planned.  We are still seeing growing numbers of IPv6 utilization in the Rancher customer base.

**Comment by brandond** [comment]
It was closed due to lack of any specific things in rke2 that still need to be documented.

If rancher doesn't work ipv6 only, thats not an rke2 issue. This is not the place for anything regarding rancher or rancher provisioning.

**Comment by Tejeev** [comment]
@brandond My apologies for my incorrect semantics; I say Rancher customers because I work for our Rancher Support team and all of our customers use RKE2.  
Thus, in my mind Rancher customers are RKE2 customers, but I see why outside the support team, that would be confusing.

That aside, if I understand correctly you're saying that this should have been closed as 'done'?

**Comment by brandond** [comment]
If you feel there's still something to address, please say what.

**Comment by Tejeev** [comment]
The thing to address is the state of the ticket. You're the one who's usually super semantic about these sorts of things not me.

**Comment by Tejeev** [comment]
What I'm asking is was this ticket closed because it was felt that the enumerated points were addressed? If not why? The ticket was closed without a comment or any explanation as one we are not going to address.

**Comment by brandond** [comment]
I asked questions in https://github.com/rancher/rke2-docs/issues/235#issuecomment-2229286326, none of which were answered. There was a response which addressed none of the questions, after which this issue sat untouched for two years.

I don't know what you expect after two years of inactivity... if you have something specific you want, spell it out in a new issue.
